---
- name: Criar Cluster EMR com Ansible via AWS CLI
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    cluster_name: "NOTE"
    release_label: "emr-6.15.0"
    ec2_key_name: "aula12"
    ec2_instance_profile: "EMR_EC2_DefaultRole"
    service_role: "EMR_DefaultRole"
    instance_type: "m5.xlarge"
    instance_count: 3
    region: "us-east-1"

  tasks:
    - name: Criar cluster EMR
      shell: |
        aws emr create-cluster \
          --name "{{ cluster_name }}" \
          --release-label "{{ release_label }}" \
          --applications Name=Hadoop Name=Spark \
          --ec2-attributes KeyName={{ ec2_key_name }},InstanceProfile={{ ec2_instance_profile }} \
          --service-role {{ service_role }} \
          --instance-type {{ instance_type }} \
          --instance-count {{ instance_count }} \
          --region {{ region }} \
          --query 'ClusterId' \
          --output text
      register: emr_cluster

    - name: Mostrar ID do cluster criado
      debug:
        msg: "Cluster EMR criado com ID: {{ emr_cluster.stdout }}"

    - name: Aguardar até o cluster estar em estado RUNNING ou WAITING
      shell: |
        aws emr describe-cluster \
          --cluster-id {{ emr_cluster.stdout }} \
          --query "Cluster.Status.State" \
          --output text \
          --region {{ region }}
      register: cluster_state
      retries: 30           # tenta até 30 vezes
      delay: 60             # espera 60 segundos entre as tentativas
      until: cluster_state.stdout in ["WAITING", "RUNNING"]

    - name: Obter DNS público do Master
      shell: |
        aws emr describe-cluster \
          --cluster-id {{ emr_cluster.stdout }} \
          --query "Cluster.MasterPublicDnsName" \
          --output text \
          --region {{ region }}
      register: master_dns

    - name: Exibir DNS público do Master
      debug:
        msg: "Master DNS: {{ master_dns.stdout }}"
